### ISSUE TITLE
gap time in wave.java

### ISSUE THREAD

**Issue by Golgorz** [john990/WaveView#4]
Checking the code, found out this:
long gap = 16 - System.currentTimeMillis() - start;
File: Wave.java -- Class: RefreshProgressRunnable
i am always getting negative values...why not make it:
long gap = 16 - (System.currentTimeMillis() - start);
so it gets a positive number always and we can delete gap < 0 ? 0 : gap check?

**Comment by john990** [comment]
You are right, I have fix it int lastest code,thank you!
