### ISSUE TITLE
Gradle dependency

### ISSUE THREAD

**Issue by romaloma** [john990/WaveView#7]
Could you provide this option? :)
Good work! Greetings

**Comment by jitpack-io** [comment]
Hi!
It's possible to install it as a Gradle dependency from: https://jitpack.io/#john990/WaveView/16a10c1f9b
Would be nice if there was a GitHub release of WaveView as well.

**Comment by SepJaPro24** [comment]
this dependency : compile 'com.github.john990:WaveView:16a10c1f9b'
and this one : compile 'com.github.john990:WaveView:3da6d4baa'
no working :(
could you please provide dependency ?
Nice job by the way

**Comment by john990** [comment]
Has update readme : )
